name: "Build with nix"

on:
  push:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # I would like if there was a ubuntu-latest-arm but alas
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe
      - uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569
        with:
          # Cache key has been ordered with the value likely to change most frequently at the end
          # So that we can fallback by matching on prefixes
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}-${{ hashFiles('**/Cargo.lock') }}
          # If there's no cache hit, restore a cache by one of these prefixes
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}-
            nix-${{ runner.os }}-
      - run: nix build -L
